services:
  traefik:
    image: traefik:v3.6
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=Europe/Warsaw # Change this to your timezone
    networks:
      nginx-bridge:
    ports:
      - 380:80 # HTTP entryPoints
      - 3443:443 # HTTPS entryPoints
      - 8080:8080 # Dashbaord WebGui 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Docker socket to watch for Traefik
      - /docker/traefik/traefik.yml:/traefik.yml:ro # Traefik config file
      - /docker/traefik/certs:/certs # Docker volume to store the acme file for the Certifactes

networks:
  nginx-bridge:
    name: nginx-bridge
    external: true
